### ISSUE TITLE
Cannot tap kettle/homebrew-kettle: invalid syntax in tap!

### ISSUE THREAD

**Issue by rbleattler** [kettle/homebrew-kettle#2]
Trying to setup a fresh macOS installation after installing Hombrew and trying to tap kettle-homebrew and I get this error:

```
$ brew tap kettle/homebrew-kettle git@github.com:kettle/homebrew-kettle.git
==> Tapping kettle/kettle
Cloning into '/usr/local/Homebrew/Library/Taps/kettle/homebrew-kettle'...
remote: Enumerating objects: 6, done.
remote: Counting objects: 100% (6/6), done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 6 (delta 0), reused 4 (delta 0), pack-reused 0
Receiving objects: 100% (6/6), done.
Error: Formula duplicating alias: /usr/local/Homebrew/Library/Taps/kettle/homebrew-kettle/Aliases/contactor
Error: Cannot tap kettle/kettle: invalid syntax in tap!
```

**Comment by jacobbudin** [comment]
@rbleattler Thanks for the report.

I've addressed this in https://github.com/kettle/homebrew-kettle/commit/274da327c7207e5aeca293673bce367b48356c67, but I should warn you that the current version of Contactor is not compatible with the latest stable Swift library. You can and should rebuild from source ([instructions](https://github.com/kettle/Contactor/#building-from-source)).

**Comment by rbleattler** [comment]
Thanks Jacob. I finally got it working when compiling from source (and doing some serious homebrew cleanup)

Robert Bleattler
Systems Administrator
267-294-6880

________________________________
